### PR TITLE
fix: Check that ace plugin is loaded after include-codeblock

### LINKED ISSUE #40: Ace template parser and plugin ordering
@azu Arf, it seems we were a bit too fast with last release. I got an error once using it in the book.
```
Template render error: (/home/user/devel/booktest/example/test.adoc) [Line 67, Column 1]
  unknown block tag: ace
```
This is weird since the tests seems to work. I think there's a problem with `{%ace%}` tag while parsing the template file.

I'll investigate that.

### PR DESCRIPTION
**Pull request by gdolle**
`gitbook-plugin-include-codeblock` must be loaded before `gitbook-plugin-ace`.

## Changelogs:
- Update readme
- Add winston plugin for color logs.
- Check gitbook plugin ordering.
    - `gitbook-plugin-ace` not required! => display warning for ace templates
    - `gitbook-plugin-ace` loaded => check ordering (return error if loaded before include-codeblock)
- Add tests for different templates (default, ace, custom)

## Related

fix #40

### CODE REVIEW

File: src/include-codeblock.js [hunk 1]
```diff
@@ -16,3 +18,17 @@ module.exports = {
         }
     }
 };
+
+try {
```
Comment (azu) [inline src/include-codeblock.js]: Can you move this check logic to separated file like `src/ace-check.js`?

File: README.md [hunk 2]
```diff
@@ -81,7 +82,23 @@ Any contribution is welcome. Propose your new templates via pull-requests.
...
-To use ace within include-codeblock, an "ace" template is required.
+To use ace within include-codeblock, you have to **load the ace plugin after include-codeblock!**
+and choose an ace temple (see [template/](templates/))
+
+```js
+{
+    "gitbook": "3.x.x",
+    "plugins" : [
+        include-codeblock,
+        ace
```
Comment (azu) [inline README.md]: wrap with `"`

File: examples/custom/book.js [hunk 3]
```diff
@@ -1,13 +1,13 @@
...
     "gitbook": "3.x.x",
-    "title": "gitbook-plugin-include-codeblock example",
+    "title": "gitbook-plugin-include-codeblock example-custom",
     "plugins": [
         "include-codeblock"
     ],
     "pluginsConfig": {
         "include-codeblock": {
-            "template": __dirname + "/user-template.hbs"
+            "template": __dirname + "user-template.hbs"
```
Comment (azu) [inline examples/custom/book.js]: It will be better that use `path.join(__dirname, "user-template.hbs")`.
(and need `const path = require("path")`)

File: .travis.yml [hunk 4]
```diff
@@ -3,4 +3,6 @@ language: node_js
 node_js: "stable"
 script:
 - npm test
-- npm run test:example
\ No newline at end of file
+- npm run test:example-default
+- npm run test:example-ace
+- npm run test:example-custom
```
Comment (azu) [inline .travis.yml:8]: 👍 Nice tests

File: src/include-codeblock.js [hunk 5]
```diff
@@ -16,3 +18,17 @@ module.exports = {
...
+    require.resolve("gitbook-plugin-ace");
```
Comment (azu) [inline src/include-codeblock.js]: Is this line needed?

or need comments 

// step1 : check abc
// step2: check def

**Review by azu — CHANGES_REQUESTED** [review]
OK. It is resonale changes.

File: src/include-codeblock.js (hunk 1 above)
Comment (gdolle) [reply src/include-codeblock.js]: ok

File: src/include-codeblock.js (hunk 5 above)
Comment (gdolle) [reply src/include-codeblock.js]: Yes, it checks if the plugin is loaded, if not it display a warning.

File: README.md (hunk 2 above)
Comment (gdolle) [reply README.md]: Oops, I'll fix that

File: examples/custom/book.js (hunk 3 above)
Comment (gdolle) [reply examples/custom/book.js]: Ok for me

**Comment by gdolle** [comment]
I'll make some change before update the PR. I'll refactor a bit the code, because book.json options does not work as expected. I'll let you know when I'm done. ;)

**Comment by gdolle** [comment]
@azu done

I'll refactor a bit the code in another PR. (plugin book options does not work as expected)

**Review by azu — APPROVED** [review]

**Comment by azu** [comment]
@gdolle Merge it and release https://github.com/azu/gitbook-plugin-include-codeblock/releases/tag/3.0.1 
Thanks.
